### ISSUE TITLE
아이템 획득

### ISSUE THREAD

**Issue by Arkru1204** [letusgraduate/Daydream#26]
# Description
아이템을 획득하는 기능
- 1, 2, 3 : 아이템 사용 (액티브 아이템만)
- Tab : 아이템 선택 (1, 2, 3 순서대로 선택되게)
    - Q : 아이템 버리기
    - W : 아이템 사용
   
# Todo
- [x] 플레이어가 아이템 습득
- [x] 습득한 아이템 UI에 표시
- [x] 1, 2, 3 키로 아이템 사용
- [x] 아이템 선택 순서대로 탭 UI
- [x] 선택된 아이템 버리기
- [x] 선택된 아이템 사용
- [x] E키로 아이템 습득
   
# ETC
탭으로 선택된 아이템은 UI에서 노란색 테두리 표시
