### ISSUE TITLE
스토리 텍스트 출력

### ISSUE THREAD

**Issue by Arkru1204** [letusgraduate/Daydream#39]
# Description
스토리 텍스트 오브젝트를 만들고 닿이면 스토리 텍스트가 UI에 출력되도록 구성합니다.
   
# Todo
- [x] 스토리 텍스트 파싱
- [x] UI에 텍스트 출력
- [x] 오브젝트 충돌로 텍스트 받아오기
   
# ETC
기타사항
