### ISSUE TITLE
플레이 스코어

### ISSUE THREAD

**Issue by Arkru1204** [letusgraduate/Daydream#42]
# Description
설명을 작성하세요.
   
# Todo
- [x] 몬스터 처치 스코어
- [x] 보유 코인 스코어
- [x] 스테이지 진행 스코어
- [x] 게임 오버 시 스코어 출력
   
# ETC
기타사항
