### ISSUE TITLE
텍스트 출력 추가

### ISSUE THREAD

**Issue by Arkru1204** [letusgraduate/Daydream#58]
# Description
스토리 텍스트 출력 추가 사항
   
# Todo
- [x] 중복 출력 방지
- [x] 출력 속도 증가
- [x] 트리거 출력 후 트리거 해제
   
# ETC
기타사항
