### ISSUE TITLE
특성 업그레이드 구현

### ISSUE THREAD

**Issue by Arkru1204** [letusgraduate/Daydream#61]
# Description
베이스 캠프에서 업글 가능
   
# Todo
- [x] 특성 창 구현
- [x] 이속 증가 + 1 ~ 4
- [x] HP 증가 + 1 ~ 4
- [x] 최종 공격력 증가 + 1 ~ 4
- [x] 일반 스킬 언락 + 1 ~ 2
- [x] 대시 스택 + 1 ~ 2
- [x] 아이템 소지 수 + 1 ~ 2
- [x] 특성 업글 시 저장
   
# ETC
* 이속은 +1씩 (3 ~ 7)
* HP는 +10씩 (100 ~ 150)
* 공격력은 +5씩 (평타 기준 10 ~ 30)
* 일반 스킬 언락은 +1씩 (1 ~ 3)
* 대시 스택은 +1씩 (1 ~ 3)
* 아이템 소지 수는 +1씩 (1 ~ 3)
